# Generated by Django 3.2.23 on 2023-11-18 21:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Upload'),
        ),
    ]
