# Generated by Django 3.2.23 on 2023-11-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, default='../default_post_ns8zax', upload_to='video/%y'),
        ),
    ]
