# Generated by Django 3.2.23 on 2023-11-18 21:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20231118_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_clip',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='video'),
        ),
    ]
