# Generated by Django 3.2.23 on 2023-11-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_upload_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_clip',
            field=models.FileField(upload_to='media/'),
        ),
    ]
