# Generated by Django 3.2.23 on 2023-11-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_upload_clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upload_clip',
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_image',
            field=models.FileField(blank=True, default='../default_post_ns8zax', upload_to='media/'),
        ),
    ]
