# Generated by Django 3.2.23 on 2023-11-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20231118_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload_image',
            new_name='upload_clip',
        ),
    ]
