# Generated by Django 3.2.23 on 2023-11-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_upload_image_post_upload_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_clip',
            field=models.FileField(blank=True, default='../default_post_ns8zax', upload_to=''),
        ),
    ]
