# Generated by Django 3.2.23 on 2023-11-19 11:59

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20231119_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_clip',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
