# Generated by Django 3.2.23 on 2023-11-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20231121_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='last_edited',
            new_name='edited_on',
        ),
    ]
