# Generated by Django 3.2.23 on 2023-12-12 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('platform', models.CharField(blank=True, choices=[('Xbox', 'Xbox'), ('Playstation', 'Playstation'), ('Steam', 'Steam'), ('Nintendo Switch', 'Nintendo Switch'), ('Discord', 'Discord')], max_length=20, verbose_name='Preferred Platform')),
                ('platform_username', models.CharField(blank=True, max_length=255, verbose_name='Platform Username')),
                ('profile_avatar', models.ImageField(default='../defaultUserImage_tuses3', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
