# Generated by Django 3.2.23 on 2023-11-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='uploaded_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_avatar',
        ),
    ]
