# Generated by Django 3.2.23 on 2023-11-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231115_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_profile',
            new_name='owner',
        ),
    ]
