# Generated by Django 3.2.23 on 2023-11-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_user_profile_profile_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='user_profile',
        ),
    ]
