# Generated by Django 3.2.23 on 2023-11-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_owner_profile_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_profile',
            new_name='owner',
        ),
    ]
