# Generated by Django 3.2.23 on 2023-11-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='platform_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
