# Generated by Django 3.2.23 on 2023-11-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_platform_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='platform_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Platfrom Username'),
        ),
    ]
