# Generated by Django 3.2.23 on 2023-11-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20231118_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='platform',
            field=models.CharField(blank=True, choices=[('Xbox', 'Xbox'), ('Playstation', 'Playstation'), ('Steam', 'Steam'), ('Nintendo Switch', 'Nintendo Switch'), ('Discord', 'Discord')], max_length=20, verbose_name='Preferred Platform'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platform_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Platfrom Username'),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
