# Generated by Django 3.2.23 on 2023-11-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20231118_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
