# Generated by Django 3.2.23 on 2023-11-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked_at',
            new_name='created_at',
        ),
    ]
