# Generated by Django 3.2.23 on 2023-11-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='started_following',
            new_name='created_at',
        ),
    ]
