# Generated by Django 3.2.23 on 2023-12-06 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_rename_last_edited_post_edited_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_choice', models.CharField(blank=True, choices=[('Call Of Duty', 'Call Of Duty'), ('Apex Legends', 'Apex Legends'), ('SpiderMan', 'SpiderMan'), ('Fifa', 'Fifa'), ('Zelda', 'Zelda'), ('Smash Bros', 'Smash Bros'), ('PUBG', 'PUBG'), ('Starfield', 'Starfield')], max_length=20, verbose_name='Preferred Platform')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='posts.post')),
            ],
        ),
    ]
