# Generated by Django 3.2.23 on 2023-12-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='experience',
            field=models.CharField(blank=True, choices=[('Noob', 'Noob'), ('Casual', 'Casual'), ('Pro', 'Pro'), ('Vetran', 'Vetran'), ('Master', 'Master'), ('God', 'God')], max_length=20, verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='games',
            name='looking_for_friends',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Looking For Friends'),
        ),
    ]
