# Generated by Django 3.2.23 on 2023-12-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20231212_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='game',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='games',
            name='profile',
        ),
    ]
