# Generated by Django 3.2.23 on 2023-12-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20231212_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='looking_for_friends',
        ),
        migrations.AddField(
            model_name='games',
            name='firends',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Firends'),
        ),
    ]
