# Generated by Django 3.2.23 on 2023-12-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20231212_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='firends',
        ),
        migrations.AddField(
            model_name='games',
            name='friends',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Friends'),
        ),
    ]
